language: php
sudo: false
php:
- 5.6
- 5.5
install: composer install
env:
  global:
    - COVERALLS_RUN_LOCALLY=1
    - ENCRYPTION_LABEL: 26b4962af0e7
script: if [ "$TRAVIS_PHP_VERSION" == '5.6' ]; then phpunit --coverage-clover=build/logs/clover.xml; else phpunit; fi 
after_success:
  - if [ "$TRAVIS_PHP_VERSION" == '5.6' ]; then php vendor/bin/coveralls -v; fi
  - if [ "$TRAVIS_PHP_VERSION" == '5.6' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then bash ./deploy.sh; fi
notifications:
  email:
    on_success: never
    on_failure: always